defmodule PersonalFinanceTracker.Repo.Migrations.AddExpensesDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:expenses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :date, :date, null: false, default: fragment("CURRENT_DATE")
      add :amount, :decimal, null: false
      add :note, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :category_id, :uuid, null: false
    end

    create table(:expense_categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:expenses) do
      modify :category_id,
             references(:expense_categories,
               column: :id,
               name: "expenses_category_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:expense_categories) do
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:expense_categories, [:name],
             name: "expense_categories_unique_name_index"
           )
  end

  def down do
    drop_if_exists unique_index(:expense_categories, [:name],
                     name: "expense_categories_unique_name_index"
                   )

    alter table(:expense_categories) do
      remove :updated_at
      remove :inserted_at
      remove :name
    end

    drop constraint(:expenses, "expenses_category_id_fkey")

    alter table(:expenses) do
      modify :category_id, :uuid
    end

    drop table(:expense_categories)

    drop table(:expenses)
  end
end
